Fix for test running on JDK 9+.  If using Spring 4.x mock objects the MockServletContext has a dependency on javax.activation that causes a java.lang.NoClassDefFoundError. - Test updated to allow the single call that triggers this in JDK9+ to continue as long as the class not found is FileTypeMap (expected).